name: CI

on: [push, pull_request]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install flake8
      run: pip install flake8
    - name: Lint Python files
      run: flake8 server --max-line-length=120 --ignore=E501,W503 --exclude=server/djangoenv,server/migrations,server/static

  lint_javascript:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: cd server/frontend && npm install
    - name: Lint JavaScript files
      run: cd server/frontend && npx eslint src --ext .js,.jsx --max-warnings=50
